### ISSUE TITLE
Input :focus box-shadow colour

### ISSUE THREAD

**Issue by mwanji** [t0m/select2-bootstrap-css#58]
As far as I can tell, the colour of a focused input's box-shadow is [hardcoded](https://github.com/t0m/select2-bootstrap-css/blob/v1.4.3/lib/select2-bootstrap.less#L269) to `rgba(82, 168, 236, 0.6)`.

With bootstrap.less, you can [modify the colour with `@input-border-focus`](https://github.com/twbs/bootstrap/blob/v3.3.1/less/mixins/forms.less#L55). Would it be possible to add this functionality?

I modified it in the following way for my project, but do not know this project and LESS well enough to know if this is a safe change:

``` less
.select2-container-active .select2-choice,
.select2-container-multi.select2-container-active .select2-choices {
  @color-rgba: rgba(red(@input-border-focus), green(@input-border-focus), blue(@input-border-focus), .6);
  border-color: @input-border-focus;
  outline: none;
  @shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 8px @color-rgba;
  .box-shadow(@shadow);
  @transition: border-color ease-in-out .15s, box-shadow ease-in-out .15s;
  .transition(@transition);
}
```
