### ISSUE TITLE
Multi select expanding while page loads

### ISSUE THREAD

**Issue by pedroreys** [t0m/select2-bootstrap-css#91]
Hi,
We are having an issue where multi select is expanding on page load, until (and I'm guessing here) js finishes loading and being processed, then it it's displayed as expected.

Here is a screenshot of the example page doing this:

![select2multiline](https://cloud.githubusercontent.com/assets/130238/8554287/558ce8ce-24bf-11e5-8953-05a2c3336023.png)
This was on Chrome for Windows, version 43.0

As I'm pretty sure I'm not the first person to run into this, is there a way to prevent this from happening that you know of?

Thanks!

**Comment by fk** [comment]
You're guessing right. ;-)

The original select2-bootstrap-css (for Bootstrap 2) seemed to handle that issue with a class `.select2` that you would apply to the original `<select>` element that Select2 would be instantiated on:

```SCSS
/**
 * This stops the quick flash when a native selectbox is shown and
 * then replaced by a select2 input when javascript kicks in. This can be
 * removed if javascript is not present
 */

select.select2 {
  height: 28px;
  visibility: hidden;
}
```

https://github.com/t0m/select2-bootstrap-css/blob/master/lib/select2-bootstrap.scss#L94-L103
